[general]
import = [
    "~/.config/alacritty/themes/themes/thelovelace.toml"
]
[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

# startup_mode = "Fullscreen"

# option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Regular"
bold.family = "JetBrainsMono Nerd Font Mono"
italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.style = "Thin"
size = 11.5
